### ISSUE TITLE
Memory leak with keep alive connections

### ISSUE THREAD

**Issue by WoZ** [LCMApps/lcm-requester#15]
All methods are affected. Issue arises in the following code on the line 27.

https://github.com/LCMApps/lcm-requester/blob/454032ae77a319c7f35c973c34632d6ab222a2af/src/SupportedMethods.js#L20-L32

`request` module actually uses node's http or https module

https://github.com/request/request/blob/a92e138d897d78ce19dd70bd1ad271c7f9c6a23d/request.js#L751

and listens `socket` event fired after a socket is assigned to this request (see [http.ClientRequest docs](https://nodejs.org/docs/latest-v10.x/api/http.html#http_event_socket)).

Than `request` module reemits mentioned `socket` event

https://github.com/request/request/blob/a92e138d897d78ce19dd70bd1ad271c7f9c6a23d/request.js#L859 

So, using `on('socket', ...` method a new listener is added each time socket is reused. With keep alive connections one socket may be used a bunch of times.

Btw, socket object has [`remoteAddress`](https://nodejs.org/docs/latest-v10.x/api/net.html#net_socket_remoteaddress) property and it's a good idea to use that data. So, `lookup` event may be listened only once to receive initial address and then to use `socket.remoteAddress` property.

Also, it's a good idea to remove `socket.on('lookup', ...` listener if error occurs

https://github.com/request/request/blob/a92e138d897d78ce19dd70bd1ad271c7f9c6a23d/request.js#L776

**Comment by OlegPoberegets** [comment]
Fixed in https://github.com/LCMApps/lcm-requester/pull/17
